apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: pastebin
  name: pastebin
  namespace: valid-namespace
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pastebin:latest
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: ssh://valid-git-repo-with-pastebin-dockerfile.git
    sourceSecret:
      name: valid-pull-secret-for-pastebin-repo
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
